const $=s=>document.querySelector(s);const state=JSON.parse(localStorage.getItem('noregrets')||'{"contacts":[],"lockedUntil":null}');let deferredPrompt=null,challengeResult=0;
const els={unlockAt:$('#unlockAt'),form:$('#contactForm'),name:$('#name'),phone:$('#phone'),list:$('#contactList'),empty:$('#emptyState'),badge:$('#listBadge'),count:$('#contactCount'),promise:$('#promise'),lock:$('#lockBtn'),hint:$('#lockHint'),pill:$('#statusPill'),countdown:$('#countdown'),statusText:$('#statusText'),dialog:$('#unlockDialog'),answer:$('#challengeAnswer'),error:$('#challengeError')};
function save(){localStorage.setItem('noregrets',JSON.stringify(state))}function tomorrow(hour=10){const d=new Date();d.setDate(d.getDate()+1);d.setHours(hour,0,0,0);return d}function localValue(d){const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,16)}
function isLocked(){return state.lockedUntil&&new Date(state.lockedUntil)>new Date()}function plural(n){return n===1?'1 kontakt':n>1&&n<5?`${n} kontakty`:`${n} kontaktů`}
function render(){const locked=isLocked();els.list.innerHTML='';state.contacts.forEach((c,i)=>{const li=document.createElement('li');li.className='contact-item';li.innerHTML=`<span class="avatar">${c.name.trim().charAt(0).toUpperCase()}</span><span class="contact-meta"><b></b><small></small></span><button class="icon-btn" aria-label="Odstranit kontakt">×</button>`;li.querySelector('b').textContent=c.name;li.querySelector('small').textContent=c.phone||'Bez kontaktu';li.querySelector('button').disabled=locked;li.querySelector('button').onclick=()=>{state.contacts.splice(i,1);save();render()};els.list.append(li)});els.empty.classList.toggle('hidden',state.contacts.length>0);els.badge.textContent=state.contacts.length;els.count.textContent=plural(state.contacts.length);els.unlockAt.disabled=locked;document.querySelectorAll('.time-chip').forEach(b=>b.disabled=locked);els.form.querySelectorAll('input,button').forEach(x=>x.disabled=locked);els.promise.disabled=locked;els.lock.disabled=!locked&&(!state.contacts.length||!els.promise.checked||!els.unlockAt.value||new Date(els.unlockAt.value)<=new Date());els.lock.classList.toggle('unlock',locked);els.lock.querySelector('span').textContent=locked?'Nouzově odemknout':'Aktivovat zámek';els.hint.textContent=locked?'Vyžaduje kontrolní úlohu':!state.contacts.length?'Přidej alespoň jeden kontakt':!els.promise.checked?'Potvrď slib svému zítřejšímu já':'Zámek nepůjde snadno zrušit';els.pill.textContent=locked?'Zámek aktivní':'Připraveno';els.pill.className=`pill ${locked?'locked':'safe'}`;els.statusText.textContent=locked?`${plural(state.contacts.length)} je chráněno do ${new Date(state.lockedUntil).toLocaleString('cs-CZ',{weekday:'long',hour:'2-digit',minute:'2-digit'})}.`:'Nastav konec zámku a přidej kontakty.';tick()}
function tick(){if(!isLocked()){if(state.lockedUntil){state.lockedUntil=null;save();render();return}els.countdown.textContent='00:00:00';return}const diff=new Date(state.lockedUntil)-new Date(),h=Math.floor(diff/36e5),m=Math.floor(diff%36e5/6e4),s=Math.floor(diff%6e4/1e3);els.countdown.textContent=[h,m,s].map(x=>String(x).padStart(2,'0')).join(':')}
document.querySelectorAll('.time-chip').forEach(b=>b.onclick=()=>{document.querySelectorAll('.time-chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');els.unlockAt.value=localValue(tomorrow(+b.dataset.hour));render()});
els.form.onsubmit=e=>{e.preventDefault();const name=els.name.value.trim(),phone=els.phone.value.trim();if(!name)return;state.contacts.push({name,phone,id:crypto.randomUUID?.()||Date.now()});els.form.reset();save();render();els.name.focus()};els.promise.onchange=render;els.unlockAt.onchange=render;
els.lock.onclick=()=>{if(isLocked()){const a=Math.floor(Math.random()*8)+4,b=Math.floor(Math.random()*7)+3;challengeResult=a*b;$('#challengeText').textContent=`Kolik je ${a} × ${b}?`;els.answer.value='';els.error.textContent='';els.dialog.showModal();els.answer.focus();return}state.lockedUntil=new Date(els.unlockAt.value).toISOString();els.promise.checked=false;save();render();navigator.vibrate?.([80,50,120])};
$('#confirmUnlock').onclick=()=>{if(Number(els.answer.value)!==challengeResult){els.error.textContent='To není správně. Zkus to znovu.';return}state.lockedUntil=null;save();els.dialog.close();render()};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').classList.add('hidden')};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
if(!els.unlockAt.value)els.unlockAt.value=localValue(tomorrow(10));render();setInterval(tick,1000);
